//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTools.FirmwareFlashersTinyTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FirmwareFlashersTinyTool {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyTools.FirmwareFlashersTinyTool.FirmwareFlashersTinyTool", typeof(FirmwareFlashersTinyTool).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point backgroundWorkerComPorts_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("backgroundWorkerComPorts.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonResetWemos_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonResetWemos.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonResetWemos_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonResetWemos.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=370,Y=67}.
        /// </summary>
        public static System.Drawing.Point buttonResetWemos_Location {
            get {
                object obj = ResourceManager.GetObject("buttonResetWemos.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=136, Height=36}.
        /// </summary>
        public static System.Drawing.Size buttonResetWemos_Size {
            get {
                object obj = ResourceManager.GetObject("buttonResetWemos.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int buttonResetWemos_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonResetWemos.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset firmware.
        /// </summary>
        public static string buttonResetWemos_Text {
            get {
                return ResourceManager.GetString("buttonResetWemos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonSelectTeensyFirmware_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonSelectTeensyFirmware.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonSelectTeensyFirmware_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonSelectTeensyFirmware.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=621,Y=34}.
        /// </summary>
        public static System.Drawing.Point buttonSelectTeensyFirmware_Location {
            get {
                object obj = ResourceManager.GetObject("buttonSelectTeensyFirmware.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=23}.
        /// </summary>
        public static System.Drawing.Size buttonSelectTeensyFirmware_Size {
            get {
                object obj = ResourceManager.GetObject("buttonSelectTeensyFirmware.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        public static int buttonSelectTeensyFirmware_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonSelectTeensyFirmware.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string buttonSelectTeensyFirmware_Text {
            get {
                return ResourceManager.GetString("buttonSelectTeensyFirmware.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonSelectWemosFirmware_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonSelectWemosFirmware.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonSelectWemosFirmware_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonSelectWemosFirmware.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=624,Y=39}.
        /// </summary>
        public static System.Drawing.Point buttonSelectWemosFirmware_Location {
            get {
                object obj = ResourceManager.GetObject("buttonSelectWemosFirmware.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=23}.
        /// </summary>
        public static System.Drawing.Size buttonSelectWemosFirmware_Size {
            get {
                object obj = ResourceManager.GetObject("buttonSelectWemosFirmware.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int buttonSelectWemosFirmware_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonSelectWemosFirmware.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string buttonSelectWemosFirmware_Text {
            get {
                return ResourceManager.GetString("buttonSelectWemosFirmware.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonTeensyUpload_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonTeensyUpload.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonTeensyUpload_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonTeensyUpload.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=509,Y=71}.
        /// </summary>
        public static System.Drawing.Point buttonTeensyUpload_Location {
            get {
                object obj = ResourceManager.GetObject("buttonTeensyUpload.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=136, Height=36}.
        /// </summary>
        public static System.Drawing.Size buttonTeensyUpload_Size {
            get {
                object obj = ResourceManager.GetObject("buttonTeensyUpload.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        public static int buttonTeensyUpload_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonTeensyUpload.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload firmware.
        /// </summary>
        public static string buttonTeensyUpload_Text {
            get {
                return ResourceManager.GetString("buttonTeensyUpload.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonWemosFlashFirmware_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonWemosFlashFirmware.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonWemosFlashFirmware_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonWemosFlashFirmware.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=512,Y=67}.
        /// </summary>
        public static System.Drawing.Point buttonWemosFlashFirmware_Location {
            get {
                object obj = ResourceManager.GetObject("buttonWemosFlashFirmware.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=136, Height=36}.
        /// </summary>
        public static System.Drawing.Size buttonWemosFlashFirmware_Size {
            get {
                object obj = ResourceManager.GetObject("buttonWemosFlashFirmware.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int buttonWemosFlashFirmware_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonWemosFlashFirmware.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload firmware.
        /// </summary>
        public static string buttonWemosFlashFirmware_Text {
            get {
                return ResourceManager.GetString("buttonWemosFlashFirmware.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=100,Y=3}.
        /// </summary>
        public static System.Drawing.Point comboBoxCards_Location {
            get {
                object obj = ResourceManager.GetObject("comboBoxCards.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=156, Height=21}.
        /// </summary>
        public static System.Drawing.Size comboBoxCards_Size {
            get {
                object obj = ResourceManager.GetObject("comboBoxCards.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int comboBoxCards_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBoxCards.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles comboBoxTeensyCardModels_Anchor {
            get {
                object obj = ResourceManager.GetObject("comboBoxTeensyCardModels.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=134,Y=8}.
        /// </summary>
        public static System.Drawing.Point comboBoxTeensyCardModels_Location {
            get {
                object obj = ResourceManager.GetObject("comboBoxTeensyCardModels.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=511, Height=21}.
        /// </summary>
        public static System.Drawing.Size comboBoxTeensyCardModels_Size {
            get {
                object obj = ResourceManager.GetObject("comboBoxTeensyCardModels.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int comboBoxTeensyCardModels_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBoxTeensyCardModels.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles comboBoxWemosCards_Anchor {
            get {
                object obj = ResourceManager.GetObject("comboBoxWemosCards.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=8}.
        /// </summary>
        public static System.Drawing.Point comboBoxWemosCards_Location {
            get {
                object obj = ResourceManager.GetObject("comboBoxWemosCards.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=544, Height=21}.
        /// </summary>
        public static System.Drawing.Size comboBoxWemosCards_Size {
            get {
                object obj = ResourceManager.GetObject("comboBoxWemosCards.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int comboBoxWemosCards_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBoxWemosCards.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelCardType_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelCardType.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelCardType_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelCardType.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=6}.
        /// </summary>
        public static System.Drawing.Point labelCardType_Location {
            get {
                object obj = ResourceManager.GetObject("labelCardType.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=52, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelCardType_Size {
            get {
                object obj = ResourceManager.GetObject("labelCardType.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int labelCardType_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelCardType.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        public static string labelCardType_Text {
            get {
                return ResourceManager.GetString("labelCardType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelTeensyCardModel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelTeensyCardModel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelTeensyCardModel_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelTeensyCardModel.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=11}.
        /// </summary>
        public static System.Drawing.Point labelTeensyCardModel_Location {
            get {
                object obj = ResourceManager.GetObject("labelTeensyCardModel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=101, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelTeensyCardModel_Size {
            get {
                object obj = ResourceManager.GetObject("labelTeensyCardModel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        public static int labelTeensyCardModel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelTeensyCardModel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a card model.
        /// </summary>
        public static string labelTeensyCardModel_Text {
            get {
                return ResourceManager.GetString("labelTeensyCardModel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelTeensySelectFirmware_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelTeensySelectFirmware.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelTeensySelectFirmware_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelTeensySelectFirmware.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=7,Y=39}.
        /// </summary>
        public static System.Drawing.Point labelTeensySelectFirmware_Location {
            get {
                object obj = ResourceManager.GetObject("labelTeensySelectFirmware.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=88, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelTeensySelectFirmware_Size {
            get {
                object obj = ResourceManager.GetObject("labelTeensySelectFirmware.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int labelTeensySelectFirmware_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelTeensySelectFirmware.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a firmware.
        /// </summary>
        public static string labelTeensySelectFirmware_Text {
            get {
                return ResourceManager.GetString("labelTeensySelectFirmware.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelWemosComPort_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelWemosComPort.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelWemosComPort_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelWemosComPort.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=11}.
        /// </summary>
        public static System.Drawing.Point labelWemosComPort_Location {
            get {
                object obj = ResourceManager.GetObject("labelWemosComPort.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=94, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelWemosComPort_Size {
            get {
                object obj = ResourceManager.GetObject("labelWemosComPort.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int labelWemosComPort_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelWemosComPort.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a COM port.
        /// </summary>
        public static string labelWemosComPort_Text {
            get {
                return ResourceManager.GetString("labelWemosComPort.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool labelWemosSelectFirmware_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelWemosSelectFirmware.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode labelWemosSelectFirmware_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelWemosSelectFirmware.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=44}.
        /// </summary>
        public static System.Drawing.Point labelWemosSelectFirmware_Location {
            get {
                object obj = ResourceManager.GetObject("labelWemosSelectFirmware.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=88, Height=13}.
        /// </summary>
        public static System.Drawing.Size labelWemosSelectFirmware_Size {
            get {
                object obj = ResourceManager.GetObject("labelWemosSelectFirmware.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int labelWemosSelectFirmware_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelWemosSelectFirmware.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a firmware.
        /// </summary>
        public static string labelWemosSelectFirmware_Text {
            get {
                return ResourceManager.GetString("labelWemosSelectFirmware.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles panelFirmwareTeensy_Anchor {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareTeensy.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=262,Y=144}.
        /// </summary>
        public static System.Drawing.Point panelFirmwareTeensy_Location {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareTeensy.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=651, Height=110}.
        /// </summary>
        public static System.Drawing.Size panelFirmwareTeensy_Size {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareTeensy.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        public static int panelFirmwareTeensy_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareTeensy.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles panelFirmwareWemos_Anchor {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareWemos.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=262,Y=30}.
        /// </summary>
        public static System.Drawing.Point panelFirmwareWemos_Location {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareWemos.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=651, Height=108}.
        /// </summary>
        public static System.Drawing.Size panelFirmwareWemos_Size {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareWemos.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int panelFirmwareWemos_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panelFirmwareWemos.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles pictureBoxCard_Anchor {
            get {
                object obj = ResourceManager.GetObject("pictureBoxCard.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode pictureBoxCard_ImeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBoxCard.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=30}.
        /// </summary>
        public static System.Drawing.Point pictureBoxCard_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBoxCard.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=250, Height=487}.
        /// </summary>
        public static System.Drawing.Size pictureBoxCard_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBoxCard.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode pictureBoxCard_SizeMode {
            get {
                object obj = ResourceManager.GetObject("pictureBoxCard.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int pictureBoxCard_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBoxCard.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles textBoxTeensyFirmware_Anchor {
            get {
                object obj = ResourceManager.GetObject("textBoxTeensyFirmware.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=134,Y=36}.
        /// </summary>
        public static System.Drawing.Point textBoxTeensyFirmware_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxTeensyFirmware.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=481, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxTeensyFirmware_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxTeensyFirmware.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int textBoxTeensyFirmware_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxTeensyFirmware.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles textBoxWemosFirmwareName_Anchor {
            get {
                object obj = ResourceManager.GetObject("textBoxWemosFirmwareName.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=41}.
        /// </summary>
        public static System.Drawing.Point textBoxWemosFirmwareName_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxWemosFirmwareName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=514, Height=20}.
        /// </summary>
        public static System.Drawing.Size textBoxWemosFirmwareName_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxWemosFirmwareName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int textBoxWemosFirmwareName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxWemosFirmwareName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
